site_name: ecv-wiki
repo_name: ECV-Lab-KULeuven/ECV-Lab-KULeuven.github.io
repo_url: https://github.com/ECV-Lab-KULeuven/ECV-Lab-KULeuven.github.io
site_url: https://ecv-lab-kuleuven.github.io/

nav:
    - Home: index.md
    - Practical:
        - Moving to Leuven: moving-to-leuven-starter-guide.md
        - Where to find us: where-to-find-rega.md
        - City Registration:
            - Registration Checklist: city-registration-checklist.md
            - City Hall Guide: leuven-city-hall-getting-started.md
            - KU Leuven Registration: registration-with-ku-leuven.md
        - Getting Around: getting-around.md
        - Lab Facilities:
            - Lab Structure: lab-structure.md
            - Parking & Bicycle Storage: rega-parking-and-bicycle-storage.md
            - Helpful People: rega-helpful-folks.md

    - PhD Resources:
        - PhD Timeline: phd-timeline.md
        - Choosing a Thematic Programme: choosing-a-thematic-programme.md
        - FWO Application: fwo-application.md
        - Perks of the PhD: perks-of-the-phd.md

    - Phylogenetics:
        - Introduction to Phylogenetics: intro-to-phylogenetics.md
        - How to Read a Tree: how-to-read-a-tree.md
        - Bayesian Phylogenetics: bayesian-phylogenetics.md
        - Maximum Likelihood Phylogenetics: maximum-likelihood-phylogenetics.md
        - Coalescent: coalescent.md
        - Phylogeography: phylogeography.md
        - Plotting Trees: plotting-trees.md

    - BEAST Tools:
        - How to Compile BEAST: how-to-compile-beast.md
        - Running BEAST: running-beast.md
        - BEAGLE (HPC): beagle-instll-hpc.md
        - BEAGLE (Local): beagle-instll-local.md
        - LogCombiner: log-combiner.md
        - TreeAnnotator: tree-annotator.md
        - Tracer: tracer.md
        - TempEst: tempest.md

    - Technical Guides:
        - HPC Getting Started: hpc-getting-started.md
        - Colors: colors.md
        - GitHub Primer: github-primer.md
        - Docker: docker.md
        - Singularity: singularity.md
        - Bioconda: bioconda.md

    - Social:
        - Leuven Bars: leuven-bars.md
        - Leuven Cafes: leuven-cafes.md
        - Leuven Restaurants: leuven-restaurants.md
        - Lab Recreation: recreation-with-the-lab.md

    - About:
        - People: people.md

theme:
    name: material
    favicon: images/ECV-cutout.png
    logo: images/ECV-cutout.png
    palette:
        - media: "(prefers-color-scheme)"
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: white
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          toggle:
              icon: material/weather-night
              name: Switch to system preference
    font:
        text: "Lora"
        code: "Ubuntu Mono"
    features:
        - announce.dismiss
        - content.action.edit
        - content.code.annotate
        - content.code.copy
        - navigation.sections
        - navigation.prune
        - navigation.top
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - search.share
        - search.suggest
        - search.highlight
        - toc.follow
        - content.footnote.tooltips
        #- navigation.footer

extra_css:
    - stylesheets/extra.css
    - https://unpkg.com/leaflet@1.3.1/dist/leaflet.css
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css

extra_javascript:
    - https://unpkg.com/leaflet@1.9.4/dist/leaflet.js
    - js/map-renderer.js

markdown_extensions:
    - admonition
    - attr_list
    - def_list
    - tables
    - md_in_html
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.critic
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.details
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.arithmatex:
          generic: true
plugins:
    - search
    - git-authors:
          show_contribution: true
          sort_authors_by: contribution
          ignore_authors:
              - 61584065+joon-klaps@users.noreply.github.com
          exclude:
              - index.md
    - git-revision-date-localized:
          type: timeago
    - awesome-pages

extra:
    generator: false
    social:
        - icon: fontawesome/brands/x-twitter
          link: https://twitter.com/LemeyLab
        - icon: fontawesome/brands/github
          link: https://github.com/ECV-Lab-KULeuven
